### ISSUE TITLE
Empty aggregated.sequences.bed.norep.bed causes seg fault

### ISSUE THREAD

**Issue by jakewendt** [RitchieLabIGH/iMOKA#11]
Sorry to report another bug without a solution.

During the aggregate step, it looks like all sequences intersect and then the `norep` file is empty. IMOKA then crashes with ...

```
***** ERROR: Requested column 4, but database file /francislab/data1/working/20191008_Stanford71/20210714-iMOKA/81/aggregated.sequences.bed.norep.bed.sorted only has fields 1 - 0.
/var/spool/slurm/d/job203747/slurm_script: line 4: 189892 Segmentation fault      singularity exec /francislab/data2/refs/singularity/iMOKA_extended-1.1.1.img iMOKA_core aggregate --input reduced.matrix --count-matrix matrix.json --mapper-config config.json --output aggregated
```

I suspect that it will run if I remove `--mapper-config config.json` but our cluster is rather full at the moment.

**Comment by RitchieLabIGH** [comment]
Hi Jake,
don't be sorry at all: your feedbacks are very useful. The crash is caused by the absence of features outside repetitive elements, a condition that I didn't consider implementing this new feature and that cause the crash of bedtools intersect. 
I have fixed the bug and you can run the new image or, removing the line 
```
  "repeats": "/blat_ref/hg38_repmask.bed"
```
in the config.json file, you can disable the repeats annotation.
Let me know if the modified image worked correctly and thank you again for your patience.
Cheers,
Claudio

**Comment by jakewendt** [comment]
Perfect. Works. Thank you again Claudio.
