### ISSUE TITLE
Sample Variation Normalization

### ISSUE THREAD

**Issue by jakewendt** [RitchieLabIGH/iMOKA#17]
Claudio,

What are your thoughts on how iMOKA performs on a dataset with differing sample sequencing depths and read lengths? 

For example, the TCGA dataset contains samples of a few X to 50X as well as read lengths from 50 to 150bp. 

Does iMOKA do enough normalization to analyze all samples together, so long as k is less than the read length?

Does iMOKA normalize simply based on the number of k-mers accounting for both read count and read length in one go?

Jake

**Comment by RitchieLabIGH** [comment]
Hi Jake,
iMOKA normalizes the data dividing each count by the total sum of k-mer counts and not by the number of k-mers:
![equaimage](https://user-images.githubusercontent.com/45385836/130020964-46b7a925-c746-4fea-bc58-80c01bcfddff.png)
Where n_i is the normalized count of the k-mer i, c_i and c_j are the raw counts of a k-mer i and j.
This allows normalizing in one go for the read length and count.
We have tested it with datasets having samples sequenced three times deeper than the ones with the lowest depth and it works fine: the signal we see was not biased by the sequencing depth and the abundances of k-mers representative of a given gene across the samples is similar to the one computed using Salmon.
Nevertheless, if the groups are unbalanced, for example one group has the majority of the samples with high depth sequences, you might have false signals of lowly expressed k-mers because they might not have been detected by the low depth samples due to the reduced resolution.
In the previous formula, we can replace the detected count ( c ) by the abundance of the k-mer (a ) times the resolution of the current sample (r):
![image](https://user-images.githubusercontent.com/45385836/130026315-c1987ab9-83bd-4e13-a626-26e38a9ce045.png)
![image](https://user-images.githubusercontent.com/45385836/130026203-8bec91ce-d521-45d2-8623-80e0e047d279.png)
![image](https://user-images.githubusercontent.com/45385836/130026629-f3865702-1b73-4b61-aa6d-6b841388028c.png)

As you can see, the normalized count is independent of the resolution.
For a k-mer with an abundance of 0.5, you need at least an r of 2 in order to have at least one k-mer in your sample. Furthermore, in the preprocessing step of iMOKA there is a min_count filter ( 5 is the default ) that ignores the k-mers with a count lower than 5. In this case, you need an r of 10 to consider the k-mer having an abundance of 0.5.

Cheers,
Claudio

**Comment by jakewendt** [comment]
Understood. Thank you.
