### ISSUE TITLE
--threads does not work?

### ISSUE THREAD

**Issue by hieunguyen411** [RitchieLabIGH/iMOKA#29]
Dear RitchieLabIGH, 

thank you for developing a great tool! I'm using this tool to generate some k-mer features for my current research. 

I notice that when I have specified the option `-t 128` to use 128 threads, it seems like the option does not work and does not affect the performance of the `preprocess.sh` function. Please see attached the two screenshots of my ongoing analysis. 

This is the command I'm using: 
```singularity exec --bind /home/hieunguyen/iMOKA/:/input iMOKA.img preprocess.sh -i source.tsv -t 128 -r 256``` 

I would like to ask if this behaviour is normal, or perhaps did I setup something wrong?

Thanks again and I'm looking forward to your reply. 
All the best
Hieu Nguyen

![Screen Shot 2022-09-16 at 00 55 43](https://user-images.githubusercontent.com/86151865/190522804-08ef0344-5588-4798-8f65-9ff853995cb8.png)
![Screen Shot 2022-09-16 at 00 55 55](https://user-images.githubusercontent.com/86151865/190522808-4592f46a-18ac-4b61-9039-d4fa10a2c164.png)

**Comment by CloXD** [comment]
Hello Hieu,
first of all, thanks for using iMOKA. 
It's normal behaviour. The preprocess.sh is essentially script that performs the following actions ( some of them only when needed or requested):
 - downloading the files
 - extract the fastq from the bam *
 - generate the fastqc report *
 - reverse one of the fastq in case of FR or RF libraries *
 - count the k-mer abundances using KMC3 *
 - create the iMOKA binary file ( iMOKA_core create ) 
 
Only the task with the asterisk* supports the multithreading, that's why it doesn't always use all the threads.
Furthermore, some of those tasks use all the threads only for portions of their processes.
With 128, I suggest dividing your input file into 10 and run the preprocess pipeline for each of them simultaneously with 12 threads each, using the parallel command or the job array if you are on a SLURM cluster. 

For the first option, the script should look something like this:
```
awk -v n_chunk=10 -v prefix="./source_chunk" '{ print > prefix "." ( NR % n_chunk ) } ' ./source.tsv
for f in ./source_chunk* ; do
     singularity exec iMOKA.img preprocess.sh -i ${f} -t 12 -r 24 > ${f}.log.out 2> ${f}.log.err & 
done
```
I hope this will help speed up your process. 
Cheers,
Claudio

**Comment by hieunguyen411** [comment]
Hello Claudio, 

thank you very much for your speedy response and the information. Trying it now :) 
Cheers,
Hieu
