### ISSUE TITLE
File not found error in iMOKA aggregate step

### ISSUE THREAD

**Issue by hl-xue** [RitchieLabIGH/iMOKA#6]
Hello, 

I am using iMOKA for k-mer analysis. When I was running iMOKA's aggregate step, there appears an "Error: file reduced.matrix doesn't exists!" at the first line of output information, but the execution was not broken and the results are not empty. I checked also that the file reduced.matrix does exist. 
In this case, I would like to know if this error message being normal ? Are the results generated correctly despite this error line ? 
Thanks in advance.

Best wishes.

**Comment by RitchieLabIGH** [comment]
Hello, 
first of all sorry for the inconvenient and thanks for using iMOKA.
It would be helpful to have at least the standard error/output. 
Without having access to the file or the log, the only guesses that I can make is that the file is partially corrupted: the test that iMOKA makes to verify the existence of the file is ios::good ( https://www.cplusplus.com/reference/ios/ios/good/ ), that gives error not only if the file doesn't exists, but also if there are errors in the opening of the file. 
Since the first line of the reduced matrix is the JSON  containing the information about how the reduction was operated, even if it's corrupted the results are not influenced by that. The "corruption" could come from an unknown character in this line ( not ASCI ). 

Few question to be able to help you:
Are you using the GUI or the CLI version? 
If the CLI, are you using docker/singularity images?

I'm improving the logging and part of the aggregation in v1.1, soon it will be in production ( master branch ).
It would be great to understand what is going on: the software is young and those kind of feedback are gold for me, so thank you!
Hoping to have news from you soon,
Cheers,
Claudio

**Comment by hl-xue** [comment]
Hi Claudio,

Thanks for your reply. I am using version CLI in Singularity. I recreated also matrix, and still have the same error as shown in the stderr below:

```
Error! file /store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/iMOKA/risk/train0/reduced.matrix doesn't exists!
Reading...Read 6087 kmers.
Space occupied: 8.883Mb
Computing edges... Done.
Building the groups
Found 1221 graphs : 
	- linear: 1221,3340
Nodes used: 3340/6087 ( 2747 discarded )
Extracting the sequences... Found 101 sequences.
Error! file /blat_ref/gencode.v29.annotation.noIR.gtf doesn't exists.
Mapping the sequences... 
###[DEBUG]: blat  -out=pslx -stepSize=5 -repMatch=2253 -minScore=30 -minIdentity=90 /blat_ref/hg38.2bit     ./sequences_2021_3_9_18_3_14.fa   ./sequences_2021_3_9_18_3_14.fa.pslx  >> ./sequences_2021_3_9_18_3_14.fa.pslx.out  2>> ./sequences_2021_3_9_18_3_14.fa.pslx.err 

Done.
Annotating...Writing the bed file of 0 sequences... 
Error: Unable to open file /blat_ref/gencode.v29.annotation.noIR.gtf. Exiting.
generated the intersection /store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/iMOKA/risk/train0/aggregated.sequences.bed.intersected.bed, parsing...Done.
Identified 0 genes.
Finding splicing....Done.
 Retrieving the genes length...done, producing the genes annotations...reduced to 0 genes.
Producing the alignment derived features...10.145Mb
done.
Done.
Recovering winners...Found 101 nodes.
Retrieving the counts...Done.
Aggregating the nodes with high correlation and in the gene or unmapped.
Masked 0 k-mers.
Done.
Writing /store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/iMOKA/risk/train0/aggregated.tsv
Done.
Good luck!

Completed in 15 minutes and 22 seconds .
Good luck!
```

My run was:
```
export IMOKA_MAX_MEM_GB=100; singularity exec -B /store:/store -B /data:/data iMOKA.img iMOKA_core aggregate -i $out_dir/reduced.matrix -o $out_dir/aggregated -c $out_dir/matrix.json -m default
```
Thanks !

Best wishes

**Comment by CloXD** [comment]
Hi, 
thanks for the log. 
The k-mers are read ( if you can check the number of lines with "wc -l reduced.matrix " it should give 6088 lines ), so probably it's a character in the first line of the file that is giving some error.
There is actually another problem with the alignment due to an error that I made generating the extended singularity image: the reference files were in /blat_ref/blat_ref/ and not just /blat_ref/ . You can solve this error downloading again the image (v1.0 or v1.1) or giving as configuration file ( -m ) to this json:

{
 "aligner": {
  "command": "blat",
  "flag_in": " ",
  "flag_multi_thread": "",
  "flag_out": " ",
  "io_order": "io",
  "options": " -out=pslx -stepSize=5 -repMatch=2253 -minScore=30 -minIdentity=90 /blat_ref/blat_ref/hg38.2bit ",
  "output_type": "pslx",
  "parallel": -1
 },
 "annotation": {
  "file": "/blat_ref/blat_ref/gencode.v29.annotation.noIR.gtf",
  "name": "DefaultAnnotation"
 }
}

Thanks to you and sorry for the troubles.
Cheers,
Claudio

**Comment by hl-xue** [comment]
Hi Claudio,

Here is my first line of reduced.matrix
```
kmer	HR_x_LR
AAAAAAAAAAAAAAAAAAAAAAAAAGATGAT	65.225
```
Is this normal ?
Also, when I do `wc -l reduced.matrix`, it has 252034 lines, instead of 6088.

For the blat step, actually I am running iMOKA without reference, so I guess maybe I can igore the error about blat ?

Thanks for your reply.

Best wishes,
Haoliang

**Comment by CloXD** [comment]
Hello,
there must be a problem in the reading of the file. You could try with this image https://github.com/RitchieLabIGH/iMOKA/releases/download/v1.1/iMOKA_extended and if it doesn't work again, I would like to replicate the error to understand what's wrong. 
If it's ok for you, this is my mail: claudio.lorenzi@igh.cnrs.fr
Cheers,
Claudio

**Comment by CloXD** [comment]
Problem solved using the environmental variable SINGULARITY_BINDPATH instead of singularity's -B flag.
